### ISSUE TITLE
Fs-extra v8, copy function gives error when using with jest

### ISSUE THREAD

**Issue by vladshcherbin** [jprichardson/node-fs-extra#687]
- **Operating System: mac os 10.13.4**
- **Node.js version: 12.1.0**
- **`fs-extra` version: 8.0.1**

Hey, 👋 

After updating `fs-extra` from v7 to v8, *jest tests* started to give error for `copy` function:

```bash
TypeError: cb.apply is not a function
```

![Screen Shot 2019-05-15 at 03 49 04](https://user-images.githubusercontent.com/6711845/57741386-4cc31900-76c5-11e9-936e-81ae3510bfca.png)

Here is same [reproduction repo](https://github.com/vladshcherbin/experiments/tree/master/fs-extra-8-jest) with [failing test](https://github.com/vladshcherbin/experiments/blob/master/fs-extra-8-jest/tests/index.test.js). The repo [has only two commits](https://github.com/vladshcherbin/experiments/commits/master/fs-extra-8-jest), one is with v7 and no error, second is just an update to v8 and with error.

I saw this from travis, which gave error for node v10 and v12, but not for v8. Here is [travis log](https://travis-ci.org/vladshcherbin/rollup-plugin-copy/builds/532557961). Rollback to v7 [removes error](https://travis-ci.org/vladshcherbin/rollup-plugin-copy/builds/532575571).

Any idea why this is happening? 🤔

**Comment by MrXyfir** [comment]
Also getting this error. Haven't had time to dig down which function is causing it but I'm not using `copy()`.

**Comment by manidlou** [comment]
hmm..! That's so weird! That error basically comes from `graceful-fs` that we use as a dependency. But we disabled that and used native `fs` in `fs-extra` v8.0.1 to use `fs.stat()` with `bigint` option.

**Comment by manidlou** [comment]
wondering if we need to disable that in the `fs/index.js` until they update their code!

**Comment by RyanZim** [comment]
Would be useful to have a non-jest example so we could get the full stack trace.

**Comment by vladshcherbin** [comment]
@RyanZim I tried same example without jest (same node version 12.1.0) and it didn't give me error.

```js
const fs = require('fs-extra')

async function run() {
  const src = 'tests/fixtures/src/asset.js'
  const dest = 'tests/fixtures/dist/asset.js'

  await fs.copy(src, dest)
}

run()
```

**Comment by vladshcherbin** [comment]
My best attempt to get error:

```bash
TypeError: cb.apply is not a function
    at /Users/shcherbin/Sites/test/experiments/fs-extra-8-jest/node_modules/graceful-fs/polyfills.js:285:20
    at FSReqCallback.oncomplete (fs.js:167:5)
```

**Comment by RyanZim** [comment]
Jest globally monkey-patches the fs module itself: https://github.com/facebook/jest/blob/bcc2b103e14912cff566cbacb0c2c3871ecb0994/packages/jest-runtime/src/cli/index.ts#L26

See https://github.com/isaacs/node-graceful-fs#global-patching for details about this.

IDK how best to work with this. Should fs-extra try to detect global monkey patching and run without `bigint`?

**Comment by RyanZim** [comment]
The root problem is that graceful-fs is broken and needs updates. Not sure how to get action there.

**Comment by manidlou** [comment]
Yeah exactly! If `graceful-fs` was updated we didn't go through all of this hassle!

**Comment by swernerx** [comment]
Anybody opened a bug/issue report on this one? Seems like more and more projects are crashing. Jest is used prettify massively right now.

**Comment by RyanZim** [comment]
The root issue is https://github.com/isaacs/node-graceful-fs/issues/158; if we could get action there, we'd be good.

**Comment by RyanZim** [comment]
`graceful-fs` issue is fixed, I'm thinking this issue should be fixed by reinstalling/regenerating the lockfiles to get the latest graceful-fs. Let me know if it's not.

**Comment by fastfrwrd** [comment]
Hm, I still seem to see the error with 8.1.0. I use `yarn ls` to double check, it's pulling 4.2.0 through but it still throws this error when using `fs.copy()` in a Jest test.

```
TypeError: cb.apply is not a function

      at ../../../node_modules/graceful-fs/polyfills.js:285:20
```

**Comment by RyanZim** [comment]
What version of graceful-fs is jest pulling in?

**Comment by fastfrwrd** [comment]
Per an `npm ls`, it's 4.2.0.

```sh
$ npm ls | grep graceful-fs
graceful-fs@4.2.0
```

**Comment by RyanZim** [comment]
I'd like to see the output of `npm ls graceful-fs`.

**Comment by vladshcherbin** [comment]
Just checked, the issue is fixed for me when using graceful-fs 4.2.0.

**Comment by fastfrwrd** [comment]
I'm going to chalk it up to some problem in our project, I also can't
reproduce with a fresh project.

**Comment by RyanZim** [comment]
@fastfrwrd Try doing a clean install/regenerating the lockfile.

**Comment by ondrej-kvasnovsky** [comment]
Yep, adding `"graceful-fs": "4.2.2"` library helped.
