### ISSUE TITLE
cb.apply is not a function

### ISSUE THREAD

**Issue by JustinLivi** [jprichardson/node-fs-extra#703]
- **Operating System:** Both locally on macOS 10.14.3 and in CI
- **Node.js version:** Seeing this on Node versions 10, 11, and 12 but not 8 and 9
- **`fs-extra` version:** Seeing when upgrading to 8.1.0 from 7.0.1

I'm not sure if the issue here lies in graceful-fs or in fs-extra.

Related issues that are closed:
https://github.com/isaacs/node-graceful-fs/issues/158
https://github.com/jprichardson/node-fs-extra/issues/687

I'm still seeing this with fs-extra@8.1.0 and graceful-fs@4.2.0:

```
TypeError: cb.apply is not a function

      at node_modules/graceful-fs/polyfills.js:285:20
```

Behavior is very inconsistent. 50% of the time everything works as expected and then it suddenly stops working. Downgrading resolves the issue.

**Comment by RyanZim** [comment]
Please post output of `npm ls graceful-fs` in your project.

Also, do you have jest installed?

**Comment by JustinLivi** [comment]
hmm yes I do have jest installed. Looks like lots of packages are relying on graceful-fs 4.1:
```
rollback@0.2.5
├─┬ conventional-changelog-cli@2.0.21
│ └─┬ conventional-changelog@3.1.8
│   └─┬ conventional-changelog-core@3.2.2
│     ├─┬ get-pkg-repo@1.4.0
│     │ └─┬ meow@3.7.0
│     │   └─┬ read-pkg-up@1.0.1
│     │     └─┬ read-pkg@1.1.0
│     │       ├─┬ load-json-file@1.1.0
│     │       │ └── graceful-fs@4.1.15  deduped
│     │       └─┬ path-type@1.1.0
│     │         └── graceful-fs@4.1.15  deduped
│     └─┬ read-pkg@3.0.0
│       └─┬ load-json-file@4.0.0
│         └── graceful-fs@4.1.15  deduped
├─┬ fs-extra@8.1.0
│ ├── graceful-fs@4.2.0 
│ └─┬ jsonfile@4.0.0
│   └── graceful-fs@4.1.15 
├─┬ jest@24.3.1
│ └─┬ jest-cli@24.3.1
│   ├─┬ @jest/core@24.3.1
│   │ ├─┬ @jest/transform@24.3.1
│   │ │ ├── graceful-fs@4.1.15  deduped
│   │ │ └─┬ write-file-atomic@2.4.1
│   │ │   └── graceful-fs@4.1.15  deduped
│   │ ├── graceful-fs@4.1.15  deduped
│   │ ├─┬ jest-haste-map@24.3.1
│   │ │ └── graceful-fs@4.1.15  deduped
│   │ ├─┬ jest-runner@24.3.1
│   │ │ └── graceful-fs@4.1.15  deduped
│   │ └─┬ jest-runtime@24.3.1
│   │   └── graceful-fs@4.1.15  deduped
│   └─┬ jest-util@24.3.0
│     ├─┬ @jest/source-map@24.3.0
│     │ └── graceful-fs@4.1.15  deduped
│     └── graceful-fs@4.1.15  deduped
└─┬ typedoc@0.14.2
  └─┬ fs-extra@7.0.1
    └── graceful-fs@4.1.15  deduped
```

**Comment by JustinLivi** [comment]
This is the first line that fails: https://github.com/JustinLivi/rollback/blob/dev/src/directory.test.ts#L19

Once that one fails, all subsequent `stat` calls fail with the same issue. But I can get it to work briefly if I comment out the first two stat calls, run, and then uncomment.

Seems like maybe could be a weird jest interaction?

**Comment by RyanZim** [comment]
Jest monkey-patches the `fs` module with `graceful-fs`. If you do a reinstall/regeneration of lockfile so that all instances of `graceful-fs` under `jest` are v4.2+, your issue should be fixed.

**Comment by JustinLivi** [comment]
@RyanZim thanks, that's surprising behavior from jest. Installing graceful-fs as a direct dependency resolved the issue for me. 👍

**Comment by mdimai666** [comment]
Im just download zip ``https://github.com/isaacs/node-graceful-fs`` to ``/usr/local/lib/node_modules/``
and extract with name **graceful-fs**
